#The SRC dirs
SRSC=

#Linker dirs (Lib)
LNKDIR=./Lib

#Linker flag
LNKFLAGS=-l$(LNKDIR)

#inlude dir
INCDIR=./Inlcude

#include flags
INCFLAGS=

#compiler
CC=g++

#compiler flags
CFLAGS=-w

#OBJS
OBJS=

#Name of the executable
OBJ=

all :

