IDIR =./Include
CC=gcc
CFLAGS=-I$(IDIR)

ODIR=obj
LDIR=../Lib

LIBS=-lm

# I need to figure out what the dependencies are,
# that is I need to list all the header files I think?
_DEPS = # all header files 
DEPS = $(patsubst %,%(IDIR)/%,$(_DEPS))

unhingenmake: 
