#Linker dirs (Lib)
LNKDIR=./Lib
#Linker flag
LNKFLAGS=-l$(LNKDIR)
#inlude dir
INCDIR=./Inlcude
#include flags
INCFLAGS=
#compiler
CC=g++
#compiler flags
CFLAGS=-w
OBJDIR=BuildNix
OBJS= entity.o sprite.o camera.o orthographiccamera.o perspectivecamera.o \
      shader.o texture2d.o basicvao.o modeltransform.o texture2dvao.o vao.o \
      texture2dvertex.0 vertex.o mesh.o aabb.o convexshape.o physics2d.o \
      includes.o types.o display.o error.o out.o shaderutils.o 

$(ObjDir): $(OBJS)

